#!/usr/bin/env sh
ln -sf /opt/fnipaplay/fnipaplay /usr/bin/fnipaplay
chmod +x /usr/bin/fnipaplay
update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
exit 0