            - name:  fnipaplay
  # You may pin to the exact commit or the version.
  # uses: Oberhauser-Dev/flutter-release-action@68fa6db01a15f34ab01dc787486f0b50ebbb0938
  uses: Oberhauser-Dev/flutter-release-action@v0.1.3
  with:
    # Authorized secret GitHub Personal Access Token. Defaults to github.token
    token: # optional, default is ${{ github.token }}
    # Specifies the working directory where the command is run.
    working-directory: # optional, default is ./
    # Whether the process should only run dry
    dry-run: # optional, default is true
    # The name of the app executable
    app-name: 
    # Semantic version of the release, see https://semver.org/
    app-version: # optional, default is ${{ github.ref_name }}
    # The tag of the release, could be the same as the version
    tag: # optional, default is ${{ github.ref }}
    # Add options such as "--dart-define" to the flutter build command
    build-args: # optional, default is 
    # Build one of the following options: apk, aab, web, ipk, macos, windows, debian
    build-type: # optional, default is 
    # At which stage the app should be published: production, beta, alpha, internal
    publish-stage: # optional, default is 
    # The distributor on which the app should be published: android-google-play, web-server, ios-app-store, mac-app-store, windows-ms-store, linux-ubuntu, linux-snap
    publish-distributor: # optional, default is 
    # The Keystore file as base64 string
    android-keystore-file-base64: # optional, default is 
    # The Keystore Password
    android-keystore-password: # optional, default is 
    # The key alias of the keystore
    android-key-alias: # optional, default is 
    # The password of the key alias of the keystore
    android-key-password: # optional, default is 
    # The Google Play Credentials Json file as base64 string
    publish-android-fastlane-secrets-json-base64: # optional, default is 
    # The Apple ID / iTunes username
    ios-apple-username: # optional, default is 
    # The key id of your App Store Connect API key, see https://appstoreconnect.apple.com/access/integrations/api
    ios-api-key-id: # optional, default is 
    # The issuer id of your App Store Connect API key, see https://appstoreconnect.apple.com/access/integrations/api
    ios-api-issuer-id: # optional, default is 
    # The private App Store Connect API key as base64 string, see https://appstoreconnect.apple.com/access/integrations/api
    ios-api-private-key-base64: # optional, default is 
    # The content provider id, also known as `itc_team_id` in fastlane
    ios-content-provider-id: # optional, default is 
    # The team id, also known as `team_id` in fastlane
    ios-team-id: # optional, default is 
    # Whether your team is in the Apple Developer Enterprise Program
    ios-team-enterprise: # optional, default is false
    # The private key (as base64 string) connected to the Distribution certificate
    ios-distribution-private-key-base64: # optional, default is 
    # The certificate (as base64 string) connected to the Provisioning profile used to sign the app
    ios-distribution-cert-base64: # optional, default is 
    # The hoster of the web app, e.g. the domain or ip address
    publish-web-host: # optional, default is 
    # The Web servers path to your html space of the app
    publish-web-path: # optional, default is 
    # The Web server SSH port
    publish-web-ssh-port: # optional, default is 
    # The Web server SSH user
    publish-web-ssh-user: # optional, default is 
    # The private ssh key (as base64 string) of this GitHub action server
    publish-web-ssh-private-key-base64: # optional, default is 
          
