---
    name: "PR workflow"

    on:
      pull_request:
        types: [opened, synchronize, reopened]
    
    jobs:
      flutter-build-windows:
        name: "Release for windows"
        runs-on: "windows-latest"
        permissions: write-all
    
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - run: choco install yq
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
              cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
              cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
              pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
              pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          - name: Set up Java
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '18'
          - run: flutter pub get
          - run: flutter build windows   
          - run: Compress-Archive build/windows/x64/runner/Release/* fnipaplay_windows_canary_amd64.zip
          - name: Upload windows outputs
            uses: actions/upload-artifact@v4
            with:
              name: windows_outputs
              path: |
                fnipaplay_windows_*.zip

      flutter-build-linux:
        name: "Release for Linux"
        runs-on: "ubuntu-latest" 
        permissions: write-all
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Install dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y clang cmake libgtk-3-dev ninja-build unzip libasound2-dev
            shell: bash
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - name: Get Flutter dependencies
            run: flutter pub get
            shell: bash
          - name: Build Flutter for Linux
            run: flutter build linux
            shell: bash
          - name: Package linux build output
            run: |
              # Tarball package
              tar -zcvf fnipaplay_linux_canary_amd64.tar.gz -C build/linux/x64/release/bundle .

              # Debian package
              mkdir fnipaplay_linux_canary_amd64
              cd fnipaplay_linux_canary_amd64
              mkdir -p opt/fnipaplay
              mkdir -p usr/share/applications
              mkdir -p usr/share/icons/hicolor/512x512/apps
              cp -r ../build/linux/x64/release/bundle/* opt/fnipaplay
              cp -r ../assets/linux/DEBIAN .
              chmod 0755 DEBIAN/postinst
              chmod 0755 DEBIAN/postrm

              cat>DEBIAN/control<<EOF
              Maintainer: madoka773 <valigarmanda55@gmail.com>
              Package: Fnipaplay
              Version: 0.0.1
              Section: x11
              Priority: optional
              Architecture: amd64
              Essential: no
              Installed-Size: 34648
              Description: A cross platform danmaku video player.
              Homepage: https://github.com/MCDFsteve/FnipaPlay
              Depends: ffmpeg
              EOF

              cp ../assets/linux/io.github.MCDFsteve.FnipaPlay.desktop usr/share/applications
              cp ../assets/images/logo512.png usr/share/icons/hicolor/512x512/apps/io.github.MCDFsteve.FnipaPlay.png

              cd ..
              dpkg-deb --build fnipaplay_linux_canary_amd64
            shell: bash

          - name: Upload linux outputs
            uses: actions/upload-artifact@v4
            with:
              name: linux_outputs
              path: |
                fnipaplay_linux_*.tar.gz
                fnipaplay_linux_*.deb